server:
  port: 9001
  servlet:
    context-path: /springboot/practice/upload

logging:
  level:
    com.xybert.springbootupload: debug

spring:
  servlet:
    multipart:
      enabled: true
      # 单文件大小限制
      max-file-size: 100MB
      # 总上传大小限制
      max-request-size: 10000MB
  web:
    resources:
      static-locations: classpath:static/

file:
  upload:
    path: static/