server:
  port: 9001
  servlet:
    context-path: /springboot/practice/upload

logging:
  level:
    com.xybert.springbootupload: debug

spring:
  servlet:
    multipart:
      enabled: true
      # 单文件大小限制
      max-file-size: 10MB
      # 总上传大小限制
      max-request-size: 10MB