server:
  port: 9001
  servlet:
    context-path: /springboot/practice/flyway

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-practice?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  flyway:
    # 开启flyway版本控制
    enabled: true
    # metadata版本控制信息表，默认为flyway_schema_history，如果没有flyway_schema_history表， 在执行flyway migrate命令之前, 必须先执行flyway baseline命令
    table: flyway_schema_history
    # 设置为true后flyway将在需要baseline的时候，自动执行一次baseline。
    baseline-on-migrate: true
    # 指定baseline的版本号,默认值为1,低于该版本号的sql文件, migrate时会被忽略
    baseline-version: 1
    # 字符编码,默认为UTF-8
    encoding: UTF-8
    # 是否允许不按顺序迁移 开发建议true,生产建议false
    # out-of-order: true
    # sql脚本路径，多个路径使用逗号分隔，默认值为classpath:db/migration
    locations: classpath:db/migration
    # flyway的clean命令会删除指定schema下的所有table, 生产务必禁掉。这个默认值是false，理论上作为默认配置是不科学的。
    clean-disabled: true
    # 需要flyway管控的schema list，缺省的话, 使用spring.datasource.url配置的schema
    # 可以指定多个schema, 仅会在第一个schema下建立metadata表, 也仅在第一个schema应用migration sql脚本
    # 但flyway Clean命令会依次在这些schema下都执行一遍。所以为确保生产，clean-disabled为true
    # schemas: flyway
    # 执行迁移时是否自动调用验证，当你的版本不符合逻辑，比如，你先执行了DML而没有对应的DDL时会抛出异常
    validate-on-migrate: true
