server:
  port: 9001
  servlet:
    context-path: /springboot/practice/security

logging:
  level:
    com.xybert.springbootsecurity: debug
    org.springframework.security: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-practice?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
    # 指定数据库类型
    database-platform: org.hibernate.dialect.MySQLDialect
    # 在日志中打印出执行的SQL语句信息
    show-sql: true
    hibernate:
      # 自动更新
      ddl-auto: update
    open-in-view: false